HEADINGS = {
    "Global utbredelse",
    "Norsk utbredelse og habitatvalg",
    "Norsk utbredelse og habitatkrav",
    "Bestandsstørrelse og bestandsutvikling",
    "Hekkebiologi",
    "Trekkforhold",
    "Trekkforløp",
    "Vandringer",
    "Global utbreiing",
    "Norsk utbreiing og habitatval",
    "Bestandsstorleik og bestandsutvikling",
    "Tyrkerdua vinterstid",
    "Bydua i vinterhalvåret",
}

MONTHS = (
    "januar", "februar", "mars", "april", "mai", "juni", "juli",
    "august", "september", "oktober", "november", "desember",
)

PATCHES_COMMON = [
    ("för", "fôr"),
    ("m”", "m²"),
    ("m*", "m²"),
    ("m?", "m²"),
    ("m²?", "m²"),
    ("m²i", "m² i"),
    ("m²*", "m² "),
    ("\"C", "°C"),
    ("*C", "°C"),
    (" iet", " i et"),
    ("o.1.", "o.l."),
    ("I m", "1 m"),
    ("1 mo", "I mo"),
    ("1 mi", "I mi"),
    ("I km", "1 km"),
    ("I million", "1 million"),
    ("I uke", "1 uke"),
    ("I 1-1", "11-1"),
    ("I I", "11"),
    ("1 1", "11"),
    ("[mange", "I mange"),
    ("1 mange", "I mange"),
    ("11ndia", "I India"),
    ("11sland", "I Island"),
    ("11rland", "I Irland"),
    ("haren ", "har en "),
    ("skjulti", "skjult i"),
    ("ekkerrelativt", "ekker relativt"),
    ("irelativt", "i relativt"),
    ("fug!", "fugl"),
    ("blirden", "blir den"),
    ("blirdet", "blir det"),
    ("T ", "I "),
    ("vetikke", "vet ikke"),
    ("fra I til", "fra 1 til"),
    ("erca", "er ca"),
    ("0. Hog", "O. Hog"),
    ("0. Carl", "O. Carl"),
    ("0. Stens", "O. Stens"),
    ("Deter", "det er"),
    ("deter", "det er"),
    ("erdet", "er det"),
    ("erden", "er den"),
    ("erikke", "er ikke"),
    ("0.1.", "o.l."),
    ("oo.l.", "o.l."),
    (" foren ", " for en "),
    ("el.1.", "el.l."),
    ("*Ø", "°Ø"),
    ("*N", "°N"),
    ("I 00", "100"),
    ("er densb", "erdensb"),
    ("itillegg", "i tillegg"),
    (" ien ", " i en "),
    (" I par", " 1 par"),
    ("Itillegg", "I tillegg"),
    ("iruge", "i ruge"),
    ("be stand", "bestand"),
    (" fraden ", " fra den "),
    (" meret ", " mer et "),
    ("avreir", "av reir"),
    ("godti ", "godt i "),
    (" aten ", " at en "),
    ("uglaer", "ugla er"),
    (" eren ", " er en "),
    ("fjærog", "fjær og"),
    ("døgnsruging", "døgns ruging"),
    (" varen ", " var en "),
    ("erreir", "er reir"),
    ("Ver den", "Verden"),
    (" somer ", " som er "),
    ("r:i", "r i"),
    ("ii ", " i"),
    ("atfer den", "atferden"),
    ("  ", " "),
    ("199 1", "1991"),
    ("199 I", "1991"),
    ("197 1", "1971"),
    ("Sval-bard", "Svalbard"),
    ("Trekkerav", "Trekker av"),
    ("enderopp", "ender opp"),
    ("tilf eller", "tilfeller"),
    ("hek ke", "hekke"),
    ("h eller", "heller"),
    ("fort eller", "forteller"),
    ("I eller 2", "1 eller 2"),
    ("1197", "I 197"),
    ("begynnelsenav", "begynnelsen av"),
    ("bare I", "bare 1"),
    (". det", ". Det"),
    (" vardet ", " var det "),
    ("avegg", "av egg"),
    ("enn I ", "enn 1 "),
    (" somtil ", " som til "),
    ("påreir", "på reir"),
    ("ica.", "i ca."),
    (" gårtil ", " går til "),
    (". ,\n", ".\n"),
    (". [ ", ". I "),
]

for word in [
    "par", "per", "intervaller", "nebb", "grensa", "nnia", "har", "skjult",
    "opptrådt", "hekker", "mangler", "funn", "sør", "vest", "øst", "nord", "høyt", "lavt",
    "lenge", "og", "overnatte", "nok", "ruge", "ruges", "ruger", "ser",
    "kun", "lever", "dels", "moh", "sted", "her", "eller", "mytingen", "Nederland", "enn",
    "som", "tallrik", "kull", "ned", "opp", "fugl", "vanligvis", "var", "felt", "opptrer",
    "raster", "snipa", "bakken", "øyer", "spurven", "vært", "tett", "ugler", "deltar",
    "etablert", "land", "produksjonen", "utbredt", "ligger", "tilbake", "kan", "ut",
    "vis", "kommer", "hekkende", "parker", "hager", "hekke", "hold", "art", "arter", "arten",
    " er", "unger", "kråka", "meisa", "vanlig", "vanligst", "ikke", "Bergen", "dessuten", "plassen",
    "synkront", "eggtapet", "Alta", "observasjoner", "den", "legges", "forekomme", "reiret",
    "trekker", "egg", "trost", "lokalt", "lokaliteter", "evne", "sand", "flyr", "svingninger",
    "variasjon", "lokaliseres", "registrert", "blir", "dødelighet", "gjerne", "monokulturer",
    "områder", "skal", "senest", "sist", "foregår", "vegetasjon", "inn", "søk", "øya", "oftest",
    "trær", "hekket", "samme", "somrer", "ugla", "lagt", "inne", "rundt", "foregått",
    "cm", "delt", "Varanger", "attraktive", "utelukkende", "vann", "sula", "størrelse",
    "Vesterålen", "dalen", "mark", "setter", "miljø", "maur", "finnes", "funnet", "mani",
    "også", "hulrom", "især", "både", "territorier", "insekter", "lerka", "alpinus", "skoger",
    "Egypt", "forekomsten",
    ]:
    PATCHES_COMMON.append((f"{word}i ", f"{word} i "))
    PATCHES_COMMON.append((f"{word.capitalize()}i ", f"{word.capitalize()} i "))

PATCHES_COMMON.append(("olog i", "ologi"))

for m in MONTHS:
    PATCHES_COMMON.append((f"i{m}", f"i {m}"))
    PATCHES_COMMON.append((f"{m}i", f"{m} i"))

COMMONLY_MERGED = (
    "relativt",
    "rundt",
    "registrert",
    "reirbygging",
    "ruger",
    "innført",
    "Danmark",
    "eller",
    "regelmessig",
    "reirfunn",
    "rimelig",
    "tilknytning",
)
